name: Deploy PostgreSQL Scripts

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Executar todos os scripts em ordem
        run: |
          for script in $(ls scripts/*.sql | sort); do
            echo "Executando $script"
            psql "$DATABASE_URL" -f "$script"
          done
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
