name: Deploy PostgreSQL Scripts

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Executar scripts SQL em ordem
        run: |
          echo "Executando 01_criarTabelas.sql"
          psql "$DATABASE_URL" -f 01_criarTabelas.sql

          echo "Executando 02_inserirTabelas.sql"
          psql "$DATABASE_URL" -f 02_inserirTabelas.sql
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
